### PR TITLE
Swap back to babel, fix runtime error location Fixes #2

### LINKED ISSUE #2: Line and columns are null for some errors
The following causes and error to be reported with null line and columns e.g. the following:

```
cool()
```

Yet, this does just fine.

```
cool
```

### PR DESCRIPTION
**Pull request by anthonykoch**
### What

- Switch back to using babel
- Fix runtime error location being incorrect #2 
- Add coverage insertion points
- Add webpack build to make sure it works in browser

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -89,13 +89,10 @@ export const getOriginalErrorPosition = async (err, sourcemap, functionId, env)
   if (errorPosition != null) {
     return await SourceMapConsumer.with(sourcemap, null, (consumer) => {
       const pos = consumer.originalPositionFor({
-        line: errorPosition.line - errorLineOffset,
+        line: 1,
```
Comment (anthonykoch) [inline lib/utils.js]: This should always be line number 1 regardless of what the error line is.
